### ISSUE TITLE
Error using example echo server

### ISSUE THREAD

**Issue by VeNoMouS** [wildfoundry/dataplicity-lomond#58]
```
Traceback (most recent call last):
  File "/tmp/test2.py", line 9, in <module>
    websocket.send_text('Hello, World')
  File "build/bdist.linux-x86_64/egg/lomond/websocket.py", line 461, in send_text
TypeError: text argument must not be bytes
```

```
#!/usr/bin/python

from lomond import WebSocket

websocket = WebSocket('wss://echo.websocket.org')

for event in websocket:
    if event.name == 'poll':
        websocket.send_text('Hello, World')
    elif event.name == 'text':
        print(event.text)
```

**Comment by VeNoMouS** [comment]
Ah, works with py3 not py2...

**Comment by willmcgugan** [comment]
On Python2.7 you will need to pass in unicode to `set_text`. Easiest solution would be to add this to the top of your file:

```python
from __future__ import unicode_literals
```

Or make it explicit by adding `u` to your strings:

```python
websocket.send_text(u'Hello World')
```

**Comment by VeNoMouS** [comment]
Ah cheers @willmcgugan
