### ISSUE TITLE
JSON Decode Error Line 1 Column 2

### ISSUE THREAD

**Issue by slidenerd** [wildfoundry/dataplicity-lomond#69]
First of all, thank you for the awesome library. The default GDAX stream works perfectly fine. 
When I tried to fetch data from [THIS](https://www.cryptocompare.com/api#-api-web-socket-) stream, it gives me a JSON Decode error however
This was my code. I am assuming nested json shouldnt be a problem or is it. Thank you for your response in advance

```
from lomond import WebSocket
websocket = WebSocket('wss://streamer.cryptocompare.com/socket.io/?transport=websocket')


for event in websocket:
    if event.name == "ready":
        websocket.send_json(SubAdd={ 'subs': ['5~CCCAGG~BTC~USD'] })
    elif event.name == "text":
        print(event.json)
```

```
disconnecting websocket
Traceback (most recent call last):
  File "cryptocompare_lomond_streamer.py", line 9, in <module>
    print(event.json)
  File "/Users/zup/.local/share/virtualenvs/zupcoinflask-hzGENYeu/lib/python3.6/site-packages/lomond/events.py", line 329, in json
    self._json = json.loads(self.text)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```

**Comment by willmcgugan** [comment]
Hi,

Glad you like Lomond.

The server isn't sending you JSON there. socket.io have their own format for messages, which I'm not familiar with.

If you print `event.text` you can see the raw data sent from the server.
