### ISSUE TITLE
TypeError('text argument must not be bytes') sending message

### ISSUE THREAD

**Issue by mmm286** [wildfoundry/dataplicity-lomond#88]
Hi!
I'm tryng to construct websocket client and when I use:
` ws.send_text("<open xmlns=\"urn:ietf:params:xml:ns:xmpp-framing\" version=\"1.0\" xml:lang=\"en\" to=\"wallapop.com\"/>")
`
It says me:

 ```
 File "/home/pi/.local/lib/python2.7/site-packages/lomond/websocket.py", line 517, in send_text
    raise TypeError('text argument must not be bytes')
TypeError: text argument must not be bytes
```
could you help me please? Thanks

**Comment by willmcgugan** [comment]
I'm guessing your on Python2.7

send_text takes a unicode string, so try `ws.send_text(u"<open...")` or use `ws.send_binary`

**Comment by mmm286** [comment]
> I'm guessing your on Python2.7
> 
> send_text takes a unicode string, so try `ws.send_text(u"<open...")` or use `ws.send_binary`

Thanks, with send_test I have other error:

```
Opening Websocket connection to the server ...
Traceback (most recent call last):
  File "login4.py", line 66, in <module>
    ws.send_text("<open xmlns=\"urn:ietf:params:xml:ns:xmpp-framing\" version=\"1.0\" xml:lang=\"en\" to=\"wallapop.com\"/>")
  File "/home/pi/.local/lib/python2.7/site-packages/lomond/websocket.py", line 517, in send_text
    raise TypeError('text argument must not be bytes')
TypeError: text argument must not be bytes
```

**Comment by willmcgugan** [comment]
> ws.send_text(u"<open...")

Please note the `u` preceding the string, which makes a string unicode, and not bytes.

**Comment by barfle** [comment]
send_text expects a text string (unicode on Python 2 / str on Python 3), not bytes. For bytes payloads, send_binary should be used. This TypeError is expected behavior, so closing as usage clarification.
